'''Each new term in Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2, the first 10 terms
will be:
          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fib.seq whose values do not exceed four million
find the sum of the even-valued terms.

working algorithm:
create def that takes input number n(ie 4,000,000)
create def that calculates next fib 
  fib take input number
  do fib = fib(n-1) + fib(n-2)
in definition check if number is even and add to result
sum result
''' 
def evenFibNumbers(n):
  result = 0
  if n == 1:
    return 1
  if n == 2:
    return 2 + result
  if n > 2:
    if n % 2 == 0:
      result += evenFibNumbers(n-1) + evenFibNumbers(n-2)
  return result
print(evenFibNumbers(400))